[package]
name = "DeepfakeHunters"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
deepfake_hunters = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
